### ISSUE TITLE
minecraft not starting with smart moving reboot

### ISSUE THREAD

**Issue by rebarakuk** [Meldexun/RenderLib#10]
**Describe the bug**
minecraft just doesn't start with smart moving reboot mod and its addons

**To Reproduce**
1. start minecraft with smart moving, its 3 addons and renderlib

**Screenshots/Videos**
![캡처](https://user-images.githubusercontent.com/97182629/178147470-ffaff66e-ff18-4ad0-a4bd-e4241afcbb24.PNG)

smart moving doesn't have config

**Versions**
RenderLib: 1.1.0
Forge: 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): 
[smart moving reboot](https://www.curseforge.com/minecraft/mc-mods/smart-moving-reboot)

smart moving and its 3 addons each have only 1 version

- No log provided

**Comment by Meldexun** [comment]
The log is needed to work on this.

**Comment by rebarakuk** [comment]
Then I must give up smartmoving because no logs were maded
