### ISSUE TITLE
[1.12.2] Incompatibility with VoxelMap

### ISSUE THREAD

**Issue by xJon** [Meldexun/RenderLib#12]
**Describe the bug**
As the title states, random crash upon singleplayer world load.

**To Reproduce**
Not sure how to reproduce, but figured it might still be useful to share!

**Versions**
RenderLib: `1.1.1`
Forge: `14.23.5.2860`
Minecraft: `1.12.2` 
Other mods (necessary to reproduce the bug): `Unknown`

**Log File**
https://mclo.gs/gQ4LG1y

**Comment by xJon** [comment]
This might be related to https://github.com/GregTechCE/GregTech/issues/1256? and also perhaps supposed to be fixed by LoliASM (which was included) thanks to https://github.com/LoliKingdom/LoliASM/commit/d7fa000e68d4810c89681f0505d301c4947ef663, alas the crash still occurred.

**Comment by xJon** [comment]
Not sure if related, and still not sure if it's even caused by your mods, but I tried downgrading to Entity Culling `5.x` without RenderLib and got a random ConcurrentModificationException upon opening [VoxelMap](https://www.curseforge.com/minecraft/mc-mods/voxelmap/files/3029445).
Log: https://mclo.gs/mdVVFCE
Edit: another completely random CME crash: https://mclo.gs/cePnhBw. Again not sure if it's caused by Entity Culling or not.

**Comment by Meldexun** [comment]
This is not related to the GregTech issue.

Old EntityCulling versions are unsupported.

**Comment by Meldexun** [comment]
You can try to reproduce the issue with this version.
[RenderLib-1.12.2-1.1.4-dev1.jar.zip](https://github.com/Meldexun/RenderLib/files/9299109/RenderLib-1.12.2-1.1.4-dev1.jar.zip)

**Comment by xJon** [comment]
Got a crash with it, seems to be due to VoxelMap: https://mclo.gs/e0Ywiqv

**Comment by Meldexun** [comment]
That's a VoxelMap issue. Placing blocks is **not** threadsafe.

**Comment by xJon** [comment]
I got a couple more crashes not mentioning VoxelMap:
https://mclo.gs/80HuT6r
https://mclo.gs/ZyTR3sP
Probably still are caused due to it, I will try reaching out to the VoxelMap author although they don't seem to be active.
(I can also confirm the game does not crash in the same way when Entity Culling / RenderLib are not installed)
Edit: this appears in the log before the crash: https://mclo.gs/1Tw40yt

**Comment by xJon** [comment]
This is resolved by using the latest version of [VoxelMapFixes](https://github.com/ACGaming/VoxelMapFixes/releases).
