### ISSUE TITLE
[1.12.2] Client Crash on Start with StorageDrawers

### ISSUE THREAD

**Issue by BartolomeoDR** [Meldexun/RenderLib#13]
Client Crash on Start

Versions
RenderLib-1.12.2-1.1.4.jar
EntityCulling-1.12.2-6.2.2.jar
!mixinbooter-5.0
Forge: 14.23.5.2860
Minecraft: 1.12.2

Other mods: 
StorageDrawers-1.12.2-5.4.2.jar

**Log File**
https://mclo.gs/6RVx9jX

**Comment by NordicGamerFE** [comment]
Can confirm i have the same issue. older versions of RenderLib did not give me this issue

**Comment by Meldexun** [comment]
~Have you tried deleting the old config?~

**Comment by Meldexun** [comment]
Another mod is missing a dependency which causes forge to not start normally and instead try to show the missing dependencies screen. Though for some reason showing the missing dependencies screen also loads the configs which causes RenderLib to crash because other parts of the mod were not loaded.
