### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Kasia1403** [Meldexun/RenderLib#14]
[crash-2022-08-13_12.12.31-client.txt](https://github.com/Meldexun/RenderLib/files/9331210/crash-2022-08-13_12.12.31-client.txt)

**Comment by Kasia1403** [comment]
Whyyy label unconfirmed ?

**Comment by Meldexun** [comment]
Use the issue template.

**Comment by Kasia1403** [comment]
May I know why uploading crash report is not enough ? I don't understand issue templates.

**Comment by Kasia1403** [comment]
Is it possible that my crash issue is because of outdated config file ?

**Comment by Kasia1403** [comment]
Could You explain me what exactly should I write in Your issue template ? What does it mean "to reproduce issue" ?
