### ISSUE TITLE
Valkyrien Skies Causes Crash

### ISSUE THREAD

**Issue by HiddenByNight** [Meldexun/RenderLib#16]
openGLDebugOutput has been enabled.

Using Valkyrien Skies (along with its necessary addons) with RenderLib causes a crash when I load a world.

- [x] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

**To Reproduce**
Load a world with RenderLib, Valkyrien Skies, Valkyrien Skies World and Valkyrien Skies Control installed. I once managed to load a superflat world and then the game crashed when I placed the rudder block from VS, but I can't reproduce that.

**Versions**
RenderLib: 1.1.4
Forge: 14.23.5.2859
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug):  Valkyrien Skies 1.1.7, Valkyrien Skies World 1.0.0, Valkyrien Skies Control 1.1.1

**Hardware**
CPU: Intel Core i7 7700HQ
RAM: 16 GB DDR4
GPU: NVIDIA GeForce GTX 1060 with Max-Q Design
VRAM: 6 GB GDDR5

**Log File**
https://gist.github.com/HiddenByNight/18b2193144b52ab386dbdf6ec6e7bc80

I also made the following changes to renderlib.cfg but it didn't help:
Added the lines vs_control=100,100,100 and valkyrienskies=100,100,100 to entityBoundingBoxGrowthList
Added the lines vs_control=20,20,20 and valkyrienskies=20,20,20 to tileEntityBoundingBoxGrowthList
Added the lines vs_control and valkyrienskies to tileEntityCachedBoundingBoxBlacklist

**Comment by HiddenByNight** [comment]
Update: Reverting to RenderLib 1.1.1 fixes the issue.

**Comment by Meldexun** [comment]
Fixed in v1.12.2-1.1.7
