### ISSUE TITLE
Reporting Client Crash

### ISSUE THREAD

**Issue by Srdjan-V** [Meldexun/RenderLib#2]
**Log File**
https://pastes.dev/YRaaI7z5ME

**Versions**
Nothirium:0.1.1-beta
Entity Culling:6.0.1-beta
RenderLib: 1.0.5
Forge: latest
Minecraft: 1.12.2

**Comment by Meldexun** [comment]
> Forge: latest

This is not a valid version

Also this is clearly an incompatibility with another mod but nowhere is stated which other mod is incompatible with RenderLib. Please test what other mod is the cause of the crash.

**Comment by Srdjan-V** [comment]
>This is not a valid version

Forge is 14.23.5.2860 version.

>Also this is clearly an incompatibility with another mod but nowhere is stated which other mod is incompatible with RenderLib. Please test what other mod is the cause of the crash.

This is a bit hard to do, since i used Nothirium in a modpack with over 400 mods, and it only happened once. LoliASM suggested that most likely corporate was RenderLib, that is why i reported it here.

**Comment by Meldexun** [comment]
> This is a bit hard to do, since i used Nothirium in a modpack with over 400 mods, and it only happened once.

Exactly. But I will definitely not test 400 mods for incompatibilities for you.

**Comment by embeddedt** [comment]
@Meldexun There is an elusive bug that plagues 1.12 where mods that modify `loadedTileEntityList` directly cause CMEs. I have seen this crash before without RenderLib, I think this just happens to be one of the mods that reveals it. As a workaround to hide the issue, you could try iterating over a copy of the list instead, though I'm not sure how this will impact performance.

**Comment by Srdjan-V** [comment]
>Exactly. But I will definitely not test 400 mods for incompatibilities for you.

Nor was i expecting you to do, this issue is probably not going to be resolved since as i said it only happened once. But if by some of chance i do manage to identify the incompatibility I will be reopening this issue.
