### ISSUE TITLE
Crash and weird graphics glitch ( horizontally rounded menu )

### ISSUE THREAD

**Issue by Kasia1403** [Meldexun/RenderLib#20]
[crash-2022-09-08_12.16.27-client.txt](https://github.com/Meldexun/RenderLib/files/9525974/crash-2022-09-08_12.16.27-client.txt)

**Comment by Meldexun** [comment]
Please don't spam the issue tracker.

Also as I told you last time please use the issue template.

**Comment by Kasia1403** [comment]
I think I fixed it. Dynamic Surroundings was outdated and I updated it and now it works. I didn't see green dot next to Dynamic Surroundings in the mods menu. Maybe it's a bug with Dynamic Surroundings ?
