### ISSUE TITLE
Breaking a Dynamic Tree will crash the game.

### ISSUE THREAD

**Issue by MagmaSlime123** [Meldexun/RenderLib#24]
**Describe the bug**
Title.

**Reproducibility**
Please try to reproduce the issue with as few other mods as possible. Then check one of the following checkboxes according to your results. To check a checkbox replace the space between the square brackets with an x (like this [x]) or create the issue and check the checkbox by clicking on it.
- [X] I reproduced this issue with as few other mods as possible installed.
- [X] I am unable to reproduce this issue consistently.

**To Reproduce**
Steps to reproduce the behavior.
Break a Dynamic Tree.

**Screenshots/Videos**
N/A.

**Versions**
RenderLib: 1.2.6.
Forge: 2860.
Minecraft: 1.12.2.
Other mods (necessary to reproduce the bug): Dynamic/DramaticTrees.

**Hardware**
CPU: 
RAM: 
GPU: 
VRAM: 
I'm not a tech person. I have no idea where to get this info.

**Log File**
Both mods are mentioned all over the report.
Pastebin is either down or hates me.
https://gist.github.com/MagmaBro123/8a28c7f17b089bdf28d0f952491f4060

**Comment by Meldexun** [comment]
Why do you think that RenderLib is causing this issue?

**Comment by MagmaSlime123** [comment]
I have no idea, but both mods are mentioned all over the report. It should be obvious.

**Comment by Meldexun** [comment]
Ok. Though a mod being in the stacktrace doesn't necessarily mean that it is causing the crash. But of course trying to identify the cause that way is fine for a normal player.

Anyway there is no indication that this is caused by RenderLib and instead this just looks like a DynamicTrees issue.
