### ISSUE TITLE
Crash with Animania mod

### ISSUE THREAD

**Issue by FranklinMCA** [Meldexun/RenderLib#25]
Disclaimer: If applicable please set the `openGLDebugOutput -> enabled` config option from RenderLib to true and try to reproduce the issue.

**Describe the bug**
Game crashes when u put down Litterbox block from Animania - Cats and dogs

**Reproducibility**
Please try to reproduce the issue with as few other mods as possible. Then check one of the following checkboxes according to your results. To check a checkbox replace the space between the square brackets with an x (like this [x]) or create the issue and check the checkbox by clicking on it.
- [x] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

**To Reproduce**
Steps to reproduce the behavior.
Please keep in mind that I most likely don't know how other mods involved in this issue work. Thus terms like "Go to dimension X" should be explained in more detail because I probably don't know how to do that.
1. Just put down Litterbox block and the game instantly crashes. You cannot go back to your wold, cause the game crashes on world loading.

**Screenshots/Videos**

**Versions**
RenderLib: 1.2.8
Forge: 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): Animania Base - 2.0.3.28; Animania - Cats & Dogs - 1.0.0.28

**Hardware**
CPU: Intel Core i5 2500
RAM: 16 GB DDR3
GPU: NVIDIA GeForce GTX 950 2 GB
VRAM: 2 GB

**Log File**
https://hastebin.com/share/tabefajipu.less

**Comment by MattyWalker1** [comment]
It crashes for me with the same mods too. I also crash when I place both cat beds, the dog pillow, cat tower and dog house. For some reason running any of the preset versions of Sildur's Vibrant Shaders v1.50 with OptiFine_1.12.2_HD_U_G5 fixes the problem for me.

**Hardware**
CPU: Intel Core i7-8086K
RAM: 32 GB DDR4
GPU: NVIDIA GeForce RTX 2070
VRAM: 8 GB

**Log File**
https://gist.github.com/MattyWalker1/f633bba772b8e67172d86999933b0afa

**Comment by Meldexun** [comment]
Fixed in v1.12.2-1.3.1
