### ISSUE TITLE
NoClassDefFoundError with RandomPatches or AdvancedRocketry

### ISSUE THREAD

**Issue by SilverBeamx** [Meldexun/RenderLib#26]
**Describe the bug**
When trying to add Nothirium to FTB:Interactions 1.91, game always crashes on load with java.lang.NoClassDefFoundError: net/minecraft/client/renderer/tileentity/TileEntityRendererDispatcher
	at com.therandomlabs.randompatches.RandomPatches.containerInit(RandomPatches.java:134)
	at com.therandomlabs.randompatches.core.RPCoreContainer.<init>(RPCoreContainer.java:33)

After disabling almost every other mod in in Modpack, Nothirium included, issue still persists. Here is a log.

**Reproducibility**
-  I reproduced this issue with as few other mods as possible installed.

**Versions**
RenderLib: 1.2.8
MixinBootstrap: 1.1.0
Forge: 14.23.5.2838
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): 

**Hardware**
CPU: i5-8600k
RAM: 8Gb allocated
GPU: GTX 1060
VRAM: 6Gb

**Log File**
[crash-2023-04-27_01.44.08-client.txt](https://github.com/Meldexun/RenderLib/files/11338130/crash-2023-04-27_01.44.08-client.txt)

**Comment by ghost** [comment]
Strange, Random Patches works fine for me with Render Lib without any errors. Maybe it's because I use Mixin Booter instead of Mixin Bootstrap + Mixin Compatibility. Have you tried this?

**Comment by Meldexun** [comment]
Your Forge version is too old. Only Forge 14.23.5.2860 is supported.
