### ISSUE TITLE
Crash Updating Nothirium and RenderLib

### ISSUE THREAD

**Issue by ReportBot9009** [Meldexun/RenderLib#28]
**Describe the bug**
I updated to Nothirium 0.3.2, Renderlib 1.3.1 ---> from Nothirium 0.2.4 and Renderlib 1.2.7 (these older versions installed and running without mixinbootstrap or mixincompat as those crash the instance), and ran those on my heavily modded E2E instance. Though I downgraded Nothirium back to 0.2.4 and kept Renderlib at 1.3.1 and the same crash persisted, leading me to believe it was Renderlib more than Nothirium. Though I know nothing about coding, so I just report what I observe. Crash within seconds as seen by log: https://mclo.gs/YMbyo2G

**Reproducibility**
Please try to reproduce the issue with as few other mods as possible. Then check one of the following checkboxes according to your results. To check a checkbox replace the space between the square brackets with an x (like this [x]) or create the issue and check the checkbox by clicking on it.
- [ ] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

-Neither of those boxes apply. I am only using my modded E2E instance. I have been running this instance for many years now, recently adding Nothirium and RenderLib without any issue.

**To Reproduce**
1. Download E2E
2. Install all mods and versions from my log file.
3. Install Nothirium 0.2.4 and Renderlib 1.2.7
4. Have no issues.
5. Update Nothirium and Renderlib, while also adding required dependencies.
6. Crash =(

**Versions**
RenderLib: 1.3.1
Forge: 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): Please see log file

**Hardware**
CPU: Intel 4790K
RAM: 32GB
GPU: EVGA 3070
VRAM: 

**Log File**
https://mclo.gs/YMbyo2G

**Comment by Meldexun** [comment]
You have to update EntityCulling as well.
