### ISSUE TITLE
Spam textures errors when debug logs enabled with just renderlib installed

### ISSUE THREAD

**Issue by quentin452** [Meldexun/RenderLib#30]
Disclaimer: If applicable please set the `openGLDebugOutput -> enabled` config option from RenderLib to true and try to reproduce the issue.

**Describe the bug**
Spam textures errors when debug logs enabled wit just renderlib installed

**Reproducibility**
- [X] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

**To Reproduce**
1. Open the game
2. Open logs

Versions
RenderLib: 1.3.2
Forge: 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug):
_MixinBootstrap-1.1.0

**Hardware**
CPU: I5 10400F
RAM: 32GB DDR4
GPU: RTX 3060
VRAM: 12GB

**Log File**
[latest.log](https://github.com/Meldexun/RenderLib/files/12349793/latest.log)

**Comment by Meldexun** [comment]
This is expected behavior. This is why I don't recommend only enabling OpenGL debug output when you want to debug an issue.
