### ISSUE TITLE
Latest Valkyrie and RenderLib incompatibility

### ISSUE THREAD

**Issue by shizotoaster** [Meldexun/RenderLib#31]
## Describe the bug

***A clear and concise description of what the bug is.***

Valkyrie is incompatible with RenderLib. That didn't happen before so it is probably something with latest updates of valkyrie or RenderLib

## Reproducibility

- [x] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

## To Reproduce

***Steps to reproduce the behavior:***

1. Install Valkyrie alongside RenderLib
2. Launch the game
3. BOOM! Mixin conflict crash

## Expected behavior

Game launches and works correctly

## Logs or/and crash reports

https://mclo.gs/CdteFbu

## Versions

- Valkyrie: 0.2-Dev-8
- Red Core: 0.4-Dev-5
- ConfigAnytime: 1.0
- MixinBooter: 8.4
- RenderLib: 1.3.3

- Forge: 1.12.2 - 14.23.5.2860
- Java:  1.8.0-382
- Java JVM: Bellsoft Liberica

## Specification:

- OS: Windows 11
- CPU: Ryzen 5 5600g
- GPU: Radeon RX 570 4gb OC
- RAM Allocated: 4096mb

**Comment by Meldexun** [comment]
This should be fixed on Valkyrie's side and Desoroxxx said he will fix it but I don't know when that happens.

**Comment by Meldexun** [comment]
Fixed with Valkyrie 0.2
