### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by al-wei** [Meldexun/RenderLib#38]
Disclaimer: If applicable please set the `openGLDebugOutput -> enabled` config option from RenderLib to true and try to reproduce the issue.

**Describe the bug**
Cannot enter saves after the game crashes.
Once in the game saves, it crashes immediately.

**Reproducibility**
Please try to reproduce the issue with as few other mods as possible. Then check one of the following checkboxes according to your results. To check a checkbox replace the space between the square brackets with an x (like this [x]) or create the issue and check the checkbox by clicking on it.
- [ ] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

**To Reproduce**
Steps to reproduce the behavior.
Please keep in mind that I most likely don't know how other mods involved in this issue work. Thus terms like "Go to dimension X" should be explained in more detail because I probably don't know how to do that.

The most that may be involved is chunk generation or refreshing.
Because I'm just playing games normally. I don't do anything special.

**Screenshots/Videos**
If applicable, add screenshots or videos to help explain your problem.

**Versions**
RenderLib: RenderLib-1.12.2-1.3.4
Forge: Forge 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): 

ComplementaryUnbound_r5.1.1

DynamicSurroundings-1.12.2-3.6.1.0
DynamicSurroundingsHuds-1.12.2-3.6.0.0
animania-1.12.2-base-2.0.3.28
animania-1.12.2-catsdogs-1.0.0.28
animania-1.12.2-extra-1.0.2.28
animania-1.12.2-farm-1.0.2.28
**Hardware**
CPU: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz 2.30 GHz 8core 16
RAM: 16GB3200MHz/Allocate memory8G
GPU: NVIDIA GeForce RTX 3060 Laptop GPU
VRAM: 6G

**Log File**
Providing a log file is always necessary no matter if the game crashed or not. This also means that the crash report is not needed.
Please use a paste site to upload the log file (for example https://gist.github.com/) and provide the link to the file here.
https://gist.github.com/al-wei/c6ea12782b4a0df555d66c61cd19e2ed

**Comment by Meldexun** [comment]
This has nothing to do with RenderLib and instead is a DynamicSurroundings issue.
https://github.com/capnkirok/animaniamod/issues/510
