### ISSUE TITLE
log Recurring content

### ISSUE THREAD

**Issue by al-wei** [Meldexun/RenderLib#42]
Disclaimer: If applicable please set the `openGLDebugOutput -> enabled` config option from RenderLib to true and try to reproduce the issue.

**Describe the bug**
The log repeats as the game loads
The memory of the log file reaches 170 MB

**Reproducibility**
Please try to reproduce the issue with as few other mods as possible. Then check one of the following checkboxes according to your results. To check a checkbox replace the space between the square brackets with an x (like this [x]) or create the issue and check the checkbox by clicking on it.
- [ ] I reproduced this issue with as few other mods as possible installed.
- [x] I am unable to reproduce this issue consistently.
Too many mods 350+

**To Reproduce**
Steps to reproduce the behavior.
Please keep in mind that I most likely don't know how other mods involved in this issue work. Thus terms like "Go to dimension X" should be explained in more detail because I probably don't know how to do that.
1. Launch the game

**Screenshots/Videos**
If applicable, add screenshots or videos to help explain your problem.

**Versions**
RenderLib: RenderLib-1.12.2-1.3.5
Forge: Forge 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): 

**Hardware**
CPU: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz 2.30 GHz 8core 16
RAM: 16GB3200MHz/Allocate memory8G
GPU: NVIDIA GeForce RTX 3060 Laptop GPU
VRAM: 6G

**Log File**
Providing a log file is always necessary no matter if the game crashed or not. This also means that the crash report is not needed.
Please use a paste site to upload the log file (for example https://gist.github.com/) and provide the link to the file here.
https://gist.github.com/al-wei/dac23e8677b467cc06e1e84cdad507ae

**Comment by Meldexun** [comment]
This is an issue of Custom Loading Screen and should be reported to them.
RenderLib works as expected here but you can disable the logging of OpenGL errors in the config.
