### ISSUE TITLE
launch crash

### ISSUE THREAD

**Issue by al-wei** [Meldexun/RenderLib#45]
Disclaimer: If applicable please set the `openGLDebugOutput -> enabled` config option from RenderLib to true and try to reproduce the issue.

**Describe the bug**
launch crash
mod injection failed.

**Reproducibility**
Please try to reproduce the issue with as few other mods as possible. Then check one of the following checkboxes according to your results. To check a checkbox replace the space between the square brackets with an x (like this [x]) or create the issue and check the checkbox by clicking on it.
- [ ] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

**To Reproduce**
Steps to reproduce the behavior.
Please keep in mind that I most likely don't know how other mods involved in this issue work. Thus terms like "Go to dimension X" should be explained in more detail because I probably don't know how to do that.
1. Launch the game
2. crash

**Screenshots/Videos**
If applicable, add screenshots or videos to help explain your problem.

**Versions**
RenderLib: RenderLib-1.12.2-1.3.5
Forge: Forge 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): _supermartijn642corelib-1.1.17-forge-mc1.12

**Hardware**
CPU: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz 2.30 GHz 8core 16
RAM: 16GB3200MHz/Allocate memory8G
GPU: NVIDIA GeForce RTX 3060 Laptop GPU
VRAM: 8G

**Log File**
Providing a log file is always necessary no matter if the game crashed or not. This also means that the crash report is not needed.
Please use a paste site to upload the log file (for example https://gist.github.com/) and provide the link to the file here.
https://github.com/SuperMartijn642/SuperMartijn642sCoreLib/issues/64
https://mclo.gs/hLjOMBE

**Comment by Meldexun** [comment]
Please reproduce the issue with as few other mods as possible.

**Comment by al-wei** [comment]
> Please reproduce the issue with as few other mods as possible.

FileDirector downloads mods, but the loading sequence of mods is incorrect.

**Comment by al-wei** [comment]
mods are added during loading.

**Comment by Meldexun** [comment]
I don't underatand what you are trying to say.

The issue is not reproducible with only RenderLib and SuperMartijn642sCoreLib installed.
Please find out what mods are necessary to reproduce the issue.

**Comment by al-wei** [comment]
> > Please reproduce the issue with as few other mods as possible.
> 
> FileDirector downloads mods, but the loading sequence of mods is incorrect.

I mean, the loading order is wrong. Second successful entry into the game.

**Comment by al-wei** [comment]
There may be no solution to this issue.

**Comment by rendragnet** [comment]
I'm currently getting this with just supermartijn642corelib-1.1.17-forge-mc1.18.jar, simplemagnets-1.1.11-forge-mc1.18, OptiFine_1.18_HD_U_H3.jar, and Forge 38.0.17 in Minecraft 1.18 if that helps at all :)
