### ISSUE TITLE
Crash while launching: Incompatibility with OptiFine E3?

### ISSUE THREAD

**Issue by Fenimoure** [Meldexun/RenderLib#46]
**Describe the bug**
Game crashes while launching before even the window shows up. I think, the problem is optifine E3 incompatibility of some sort. All in the attached file.

**Reproducibility**
Please try to reproduce the issue with as few other mods as possible. Then check one of the following checkboxes according to your results. To check a checkbox replace the space between the square brackets with an x (like this [x]) or create the issue and check the checkbox by clicking on it.
- [X] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

**To Reproduce**
Steps to reproduce the behavior.
Please keep in mind that I most likely don't know how other mods involved in this issue work. Thus terms like "Go to dimension X" should be explained in more detail because I probably don't know how to do that.
1. Enable MixinBootstrap
2. Enable MixinCompatibility
3. Enable RenderLib
4. Enable EntityCulling
5. Enable OptiFine E3
6. Launch game
7. Game crashes while transforming method: RenderGlobal#renderEntities(Entity, ICamera, float)

**Versions**
RenderLib: 1.3.5
Forge: 14.23.5.2859
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug):
- _MixinBootstrap-1.1.0
- EntityCulling 6.4.3
- Mixin Compatibility
- OptiFine U E3

**Hardware**
CPU: AMD Ryzen 5 5600H (12) @ 4,28 GHz
RAM: 16GB
GPU: NVIDIA GeForce RTX 3060 Mobile / Max-Q [Discrete]

[**Log File**](https://gist.github.com/Fenimoure/f2d1b7387277730d8753a05a01ecdb50)

**Comment by Popjim** [comment]
Why are you not using the latest version of OptiFine for 1.12.2 which is OptiFine HD U G5?

**Comment by Fenimoure** [comment]
> Why are you not using the latest version of OptiFine for 1.12.2 which is OptiFine HD U G5?

It is broken with other mods and shaders. By trial I've figured out that E3 works fine both with shaders and mods (IC2 and AE2).

**Comment by Popjim** [comment]
Most newer mods don't work on older versions of OptiFine so this issue may never be fixed

**Comment by Meldexun** [comment]
Only OptiFine HD U G5 is supported.
