### ISSUE TITLE
Client crash when i change world

### ISSUE THREAD

**Issue by a08381** [Meldexun/RenderLib#5]
**Describe the bug**
Client crash when i change world

**To Reproduce**
1. use Draconic Portal from AE storage cell to my skyblock island
2. shake mouse or move before it load complete
4. client crash

**Screenshots/Videos**
If applicable, add screenshots or videos to help explain your problem.

**Versions**
RenderLib: 1.0.8
Forge: 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): 
appliedenergistics2
draconicevolution
mekanism

**Log File**
Please use a paste site to upload the log file (for example https://gist.github.com/) and provide the link to the file here:
https://pastes.dev/mQ0bM1tJZj

**Comment by Meldexun** [comment]
Please reproduce the issue with as few other mods as possible installed and provide the log file (**not** the crash report).
