### ISSUE TITLE
ConcurrentModificationException on wold load with Immersive Cables installed

### ISSUE THREAD

**Issue by Srdjan-V** [Meldexun/RenderLib#9]
**Describe the bug**
Every time i load my save near my base i produces this crash. But its not crashing if i go away and slowly approach my base. This problem started with the latest updated.

**To Reproduce**
I used the ae2 fluix and dens fluix cables a lot in my base, this is the only thing i used from IC. Other then that i have no clear way to reproduce it, but i provide the save if needed.

**Screenshots/Videos**
I did try to narrow down the problem using jprofiler, i was looking in the opposed direction of my base while taking this profile.
![image](https://user-images.githubusercontent.com/78452357/177203216-0da84785-34d5-40cb-8102-6bc65670738a.png)
![image](https://user-images.githubusercontent.com/78452357/177203285-4bb06bbc-5c3c-45df-b0ec-926394632d77.png)

**Versions**
EntityCulling: `6.1.0`
RenderLib: `1.1.0`
Forge: `14.23.5.2860`
Minecraft: `1.12.2`
Other mods:
[ImmersiveCables](https://github.com/SanAndreaP/ImmersiveCables)
[About 400 mods](https://www.curseforge.com/minecraft/modpacks/enigmatica-2-expert-extended)

**Log File**
[Log file](https://pastes.dev/DSJRwdxOvW)

**Comment by Srdjan-V** [comment]
I can confirm that my save loaded fine without IC, I will update this issue

**Comment by Meldexun** [comment]
Should be fixed in v1.12.2-1.1.1
